words = {
    "cadeira",
    "livro", 
    "lapis",
    "caixa",
    "parede",
    "barco",
    "mesa",
    "garrafa",
    "relogio",
    "macaco",
    "homem",
    "esparguete",
    "carne picada",
    "mochila",
    "planeta",
    "laranja",
    "banana",
    "peixe",
    "relampago",
    "minotauro",
    "machado",
    "aquecimento",
    "cereja",
    "pato",
    "automovel",
    "ventoinha",
    "star wars",
    "girafa",
    "zebra",
    "esquilo",
    "desumidificador"
}

return words